pipeline {

    parameters {
        string(name:'LOGIN', defaultValue: 'admin', description: 'Login here')
        password(name:'PASSWORD', defaultValue: 'password', description: 'Password here')
        string(name:'VERSION', defaultValue: 'latest', description: 'Choose the container version')
        string(name:'ACCOUNT_ID', defaultValue: '409150791641', description: 'Choose the ECR account id')
        string(name:'REPOSITORY', defaultValue: 'hft_repository', description: 'Choose the ECR repository ')
    }

    agent {label "aws-virginia"}

    environment {
        CREDENTIALS = credentials("$LOGIN")
    }

    stages {

        stage("Authorization") {
            when {
                equals(actual: "$PASSWORD", expected: "${CREDENTIALS_PSW}")
            }
            steps {
                echo "Starting authorization"
                script {
                    try {
                        if ("$PASSWORD" == "${CREDENTIALS_PSW}") {
                            echo 'Authorization successful'
                        }

                        else {
                            echo 'Wrong password, try again !'
                        }
                    } catch (Exception e) {
                        e.toString()
                        echo 'Cannot find given credentials, contact with administrator'

                    }
                }
            }
        }

        stage("Preparing environment") {
            steps {
                echo "Clean directory and make backup before pulling"
            }
        }

        stage("Container pull") {
            steps {
                script {
                    try {
                        sh '''
                        sudo su &&
                        cd /root &&
                        docker pull $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:$VERSION &&
                        docker tag $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY api_container:$VERSION &&
                        docker rmi --force $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:$VERSION
                        '''
                    } catch (Exception e) {
                        echo 'Error occurred while pulling docker image:' + e.toString()
                        sh '''
                        sudo su &&
                        cd /root &&
                        aws ecr get-login-password --region us-east-1 | \
                        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY &&
                        docker pull $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:$VERSION &&
                        docker tag $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY api_container:$VERSION &&
                        docker rmi --force $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:$VERSION
                        '''

                    }
                }
            }
        }

        stage("Run application") {
            steps {
                sh '''
                docker run -d api_container:$VERSION
                '''

            }

        }

        stage("Post build actions") {
            steps {
                echo '.....'
            }

            post {
                success {
                    echo "Slack message with success here"
                }
                failure {
                    echo "Slack message with failure here"
                }


            }

        }

    }

}